[package]
name = "nexus"
version = "0.0.4"
edition = "2021"

[dependencies]
clap = "4.5.4"
fern = { version = "0.6.2", features = ["colored"] }
humantime = "2.1.0"
log = { version = "0.4.21", features = ["serde"] }
reqwest = "0.12.4"
rocket = { version = "0.5.0", features = ["json"] }
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.200", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.60"
tokio = { version = "1.37.0", features = ["full"] }
uuid = { version = "1.8.0", features = ["v4", "fast-rng", "serde"] }
