name: Build Docker image and publish to Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  publish-image:
    name: Publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rust toolchain stable-x86_64-unknown-linux-gnu
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
      - name: Read version
        id: version
        run: echo "VALUE=$(cargo read-manifest | jq -r .version)" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nexus:latest,${{ secrets.DOCKERHUB_USERNAME }}/nexus:${{ steps.version.outputs.VALUE }},${{ secrets.DOCKERHUB_USERNAME }}/nexus:${{ github.sha }}
